package com.tz.dao;

import com.tz.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);


    Cart selectCartByUserIdAndProductId(@Param("userId") Integer userId,
                                         @Param("productId") Integer productId);

    /**
     * 查询用户购物车信息
     * @param userId
     * @return
     */
    List <Cart> selectCartByUserid(Integer userId);

    /**
     * 统计用户购物信息是否全选，返回值大于0就没有全选
     */
    int isCheckedAll(Integer userId);


    /**
     * 删除购物车某些商品
     */
    int deleteByUseridAndProductIds(@Param("userId") Integer userId,
                                    @Param("productIdList") List<Integer> productIdList);


    /**
     * 操作购物车是否选中
     */
    int selectOrsUnelectProduct(@Param("userId") Integer userId,
                              @Param("productId") Integer productId,
                              @Param("check") Integer check);

    /**
     * 统计购物车中产品的数量
     */
    int get_cart_product_count(Integer userId);


    /**
     * 查询购物车中用户已经选中的商品
     */
    List<Cart> findCartListByUserIdAndChecked(Integer userId);


    /**
     * 批量删除购物车商品
     */
    int batchDelete(List<Cart> cartList);
}